// Decompiled with JetBrains decompiler
// Type: Bullets.Logic.TablesForGoodCards.HandStrengthValuation
// Assembly: Bullets.Logic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: E7CD18E4-9E5E-4D56-8EA3-EB8C441E1D33
// Assembly location: C:\Users\Svetlio\Desktop\Bullets.Logic.dll_11-29-2015 2-46-14 AM.dll

namespace Bullets.Logic.TablesForGoodCards
{
    using TexasHoldem.Logic.Cards;

    public static class HandStrengthValuation
    {
        private const int MaxCardTypeValue = 14;

        private static readonly int[,] StartingHandRecommendationsNormalMoney = new int[13, 13]
                                                                                {
                                                                                    {
                                                                                        2,
                                                                                        1,
                                                                                        1,
                                                                                        1,
                                                                                        1,
                                                                                        1,
                                                                                        1,
                                                                                        1,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0
                                                                                    },
                                                                                    {
                                                                                        1,
                                                                                        2,
                                                                                        1,
                                                                                        1,
                                                                                        1,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0
                                                                                    },
                                                                                    {
                                                                                        1,
                                                                                        1,
                                                                                        1,
                                                                                        1,
                                                                                        1,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0
                                                                                    },
                                                                                    {
                                                                                        1,
                                                                                        1,
                                                                                        1,
                                                                                        1,
                                                                                        1,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0
                                                                                    },
                                                                                    {
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        1,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0
                                                                                    },
                                                                                    {
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        1,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0
                                                                                    },
                                                                                    {
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        1,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0
                                                                                    },
                                                                                    {
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        1,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0
                                                                                    },
                                                                                    {
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        1,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0
                                                                                    },
                                                                                    {
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        1,
                                                                                        0,
                                                                                        0,
                                                                                        0
                                                                                    },
                                                                                    {
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        1,
                                                                                        0,
                                                                                        0
                                                                                    },
                                                                                    {
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        1,
                                                                                        0
                                                                                    },
                                                                                    {
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        0,
                                                                                        1
                                                                                    }
                                                                                };

        private static readonly int[,] StartingHandRecommendationsLessThan500Money = new int[13, 13]
                                                                                     {
                                                                                         {
                                                                                             2,
                                                                                             1,
                                                                                             1,
                                                                                             1,
                                                                                             1,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0
                                                                                         },
                                                                                         {
                                                                                             1,
                                                                                             2,
                                                                                             1,
                                                                                             1,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0
                                                                                         },
                                                                                         {
                                                                                             1,
                                                                                             1,
                                                                                             1,
                                                                                             1,
                                                                                             1,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0
                                                                                         },
                                                                                         {
                                                                                             1,
                                                                                             0,
                                                                                             0,
                                                                                             1,
                                                                                             1,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0
                                                                                         },
                                                                                         {
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             1,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0
                                                                                         },
                                                                                         {
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             1,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0
                                                                                         },
                                                                                         {
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             1,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0
                                                                                         },
                                                                                         {
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             1,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0
                                                                                         },
                                                                                         {
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             1,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0
                                                                                         },
                                                                                         {
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             1,
                                                                                             0,
                                                                                             0,
                                                                                             0
                                                                                         },
                                                                                         {
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0
                                                                                         },
                                                                                         {
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0
                                                                                         },
                                                                                         {
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0,
                                                                                             0
                                                                                         }
                                                                                     };

        private static readonly int[,] StartingHandRecommendationsGreaterThan500Money = new int[13, 13]
                                                                                        {
                                                                                            {
                                                                                                2,
                                                                                                1,
                                                                                                1,
                                                                                                1,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0
                                                                                            },
                                                                                            {
                                                                                                1,
                                                                                                2,
                                                                                                1,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0
                                                                                            },
                                                                                            {
                                                                                                1,
                                                                                                0,
                                                                                                1,
                                                                                                1,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0
                                                                                            },
                                                                                            {
                                                                                                1,
                                                                                                0,
                                                                                                0,
                                                                                                1,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0
                                                                                            },
                                                                                            {
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                1,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0
                                                                                            },
                                                                                            {
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                1,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0
                                                                                            },
                                                                                            {
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                1,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0
                                                                                            },
                                                                                            {
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                1,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0
                                                                                            },
                                                                                            {
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0
                                                                                            },
                                                                                            {
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0
                                                                                            },
                                                                                            {
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0
                                                                                            },
                                                                                            {
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0
                                                                                            },
                                                                                            {
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0,
                                                                                                0
                                                                                            }
                                                                                        };

        public static CardValuationType PreFlopNormal(Card firstCard, Card secondCard)
        {
            switch (firstCard.Suit == secondCard.Suit ? (firstCard.Type > secondCard.Type ? StartingHandRecommendationsNormalMoney[14 - (int) firstCard.Type, 14 - (int) secondCard.Type] : StartingHandRecommendationsNormalMoney[14 - (int) secondCard.Type, 14 - (int) firstCard.Type]) : (firstCard.Type > secondCard.Type ? StartingHandRecommendationsNormalMoney[14 - (int) secondCard.Type, 14 - (int) firstCard.Type] : StartingHandRecommendationsNormalMoney[14 - (int) firstCard.Type, 14 - (int) secondCard.Type]))
            {
                case 0:
                    return CardValuationType.Unplayable;
                case 1:
                    return CardValuationType.Playable;
                case 2:
                    return CardValuationType.BestHand;
                default:
                    return CardValuationType.Unplayable;
            }
        }

        public static CardValuationType PreFlopGreaterThan500Money(Card firstCard, Card secondCard)
        {
            switch (firstCard.Suit == secondCard.Suit ? (firstCard.Type > secondCard.Type ? StartingHandRecommendationsGreaterThan500Money[14 - (int) firstCard.Type, 14 - (int) secondCard.Type] : StartingHandRecommendationsGreaterThan500Money[14 - (int) secondCard.Type, 14 - (int) firstCard.Type]) : (firstCard.Type > secondCard.Type ? StartingHandRecommendationsGreaterThan500Money[14 - (int) secondCard.Type, 14 - (int) firstCard.Type] : StartingHandRecommendationsGreaterThan500Money[14 - (int) firstCard.Type, 14 - (int) secondCard.Type]))
            {
                case 0:
                    return CardValuationType.Unplayable;
                case 1:
                    return CardValuationType.Playable;
                case 2:
                    return CardValuationType.BestHand;
                default:
                    return CardValuationType.Unplayable;
            }
        }

        public static CardValuationType PreFlopLessThan500Money(Card firstCard, Card secondCard)
        {
            switch (firstCard.Suit == secondCard.Suit ? (firstCard.Type > secondCard.Type ? StartingHandRecommendationsLessThan500Money[14 - (int) firstCard.Type, 14 - (int) secondCard.Type] : StartingHandRecommendationsLessThan500Money[14 - (int) secondCard.Type, 14 - (int) firstCard.Type]) : (firstCard.Type > secondCard.Type ? StartingHandRecommendationsLessThan500Money[14 - (int) secondCard.Type, 14 - (int) firstCard.Type] : StartingHandRecommendationsLessThan500Money[14 - (int) firstCard.Type, 14 - (int) secondCard.Type]))
            {
                case 0:
                    return CardValuationType.Unplayable;
                case 1:
                    return CardValuationType.Playable;
                case 2:
                    return CardValuationType.BestHand;
                default:
                    return CardValuationType.Unplayable;
            }
        }
    }
}